[package]
name = "my-gtk-app"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.0", package = "gtk4", features = ["v4_18"] }

[build-dependencies]
glib-build-tools = "0.21.0"
